deploymentWeb:
  name: web
  replicaCount: 1
  containerName: notejam
  containerImage: REPLACE_ME
  cpuRequest: 100m
  cpuLimit: 250m
  memoryRequest: 128Mi
  memoryLimit:  250Mi

deploymentDb:
  name: db
  replicaCount: 1
  containerName: database
  containerImage: postgres
  cpuRequest: 100m
  cpuLimit: 250m
  memoryRequest: 128Mi
  memoryLimit:  256Mi 

ingress:
  name: notejam
  host: "notejam.localhost"

serviceDb:
  name: db

serviceWeb:
  name: web

secretDb:
  name: notejam-credentials
  user: REPLACE_ME
  password: REPLACE_ME

imageCredentials:
  registry: https://index.docker.io/v1/
  username: REPLACE_ME
  password: REPLACE_ME


nameSpace:
  name: REPLACE_ME

configMap:
  name: dbconfig
  dbname: "nj"

PersistentVolumeClaim:
  name: data-db
  accessMode: ReadWriteOnce
  storageRequest: 2Gi
  omitStorageClassName: true
  omitVolumeName: true
