apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:21.10
      securityContext:
        # allowPrivilegeEscalation: true
        # runAsUser: 0
        privileged: true
      # volumeMounts:
      #   - name: dockersock
      #     mountPath: /var/run/docker.sock            
      command:
        - cat
      tty: true
  # volumes:
  #   - name: dockersock
  #     hostPath:
  #       path: /var/run/docker.sock      