apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:21.10
      securityContext:
        privileged: true
      command:
      - sleep
      args:
      - 99d
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
      - sleep
      args:
      - 9999999
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    restartPolicy: Never
    volumes:
    - name: kaniko-secret
      secret:
          secretName: dockercred
          items:
          - key: .dockerconfigjson
            path: config.json