apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:21.10
      securityContext:
        # allowPrivilegeEscalation: true
        # runAsUser: 0
        privileged: true
      volumeMounts:
        - name: "workspace-volume"
          mountPath: "/home/jenkins/agent"
          readOnly: false
      command:
        - cat
      tty: true
  volumes:
    - name: workspace-volume
      persistentVolumeClaim:
        claimName: jenkins-slave-pvc      