apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.statefulsetDb.name }}-deployment
  namespace: {{ .Values.nameSpace.name }}
  labels:
    service: {{ .Values.statefulsetDb.name }}
spec:
  replicas: {{ .Values.statefulsetDb.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Values.statefulsetDb.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.statefulsetDb.name }}
        tier: backend
    spec:
      containers:
        - image: {{ .Values.statefulsetDb.containerImage }}
          name: {{ .Values.statefulsetDb.containerName }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretDb.name }}
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretDb.name }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: dbname

          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: {{ .Values.statefulsetDb.cpuRequest }}
              memory: {{ .Values.statefulsetDb.memoryRequest }}
            limits:
              cpu: {{ .Values.statefulsetDb.cpuLimit}}
              memory: {{ .Values.statefulsetDb.memoryLimit }}
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: {{ .Values.PersistentVolumeClaim.name }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.PersistentVolumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.PersistentVolumeClaim.name }}