apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentWeb.name }}-deployment
  namespace: {{ .Values.nameSpace.name }}
  labels:
    service: {{ .Values.deploymentWeb.name }}
spec:
  replicas: {{ .Values.deploymentWeb.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Values.deploymentWeb.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.deploymentWeb.name }}
    spec:
      containers:
        - args:
            - bash
            - -c
            - python manage.py syncdb --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:5000
          image: {{ .Values.deploymentWeb.containerImage }}
          name: {{ .Values.deploymentWeb.containerName }}
          ports:
            - containerPort: 5000
      imagePullSecrets:
      - name: registrypullsecret
          resources:
            requests:
              cpu: {{ .Values.deploymentWeb.cpuRequest }}
              memory: {{ .Values.deploymentWeb.memoryRequest }}
            limits:
              cpu: {{ .Values.deploymentWeb.cpuLimit}}
              memory: {{ .Values.deploymentWeb.memoryLimit }}
      restartPolicy: Always