apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Values.deploymentDb.name }}
  name: {{ .Values.PersistentVolumeClaim.name }}
spec:
  accessModes: 
    - {{ .Values.PersistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.storageRequest }}