apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretDb.name }}
  namespace: {{ .Values.nameSpace.name }}
type: Opaque
data:
  user: {{ .Values.secretDb.user }}
  password: {{ .Values.secretDb.password }}