apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.deploymentDb.name }}
  name: {{ .Values.serviceDb.name }}
  namespace: {{ .Values.nameSpace.name }}
spec:
  ports:
    - name: "5432"
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.deploymentDb.name }}