apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.deploymentWeb.name }}
  name: {{ .Values.serviceWeb.name }}
  namespace: {{ .Values.nameSpace.name }}
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    service: {{ .Values.deploymentWeb.name }}